local NUI = unpack(NaowhUI)

NUI.NameplateAuras = {
	["CustomSpells2"] = {
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[377048] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Absolute Zero",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[221562] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Asphyxiate",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[31935] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Avenger's Shield",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[89766] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Axe Toss",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[710] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Banish",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[117526] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Binding Shot",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[2094] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Blind",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[105421] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Blinding Light",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[207167] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Blinding Sleet",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[451517] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Catch Out",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[179057] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Chaos Nova",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[1833] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Cheap Shot",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[324382] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Clash",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[33786] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Cyclone",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[31661] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Dragon's Breath",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[64695] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Earthgrab",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[77505] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Earthquake",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[460614] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Entangling Roots",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[339] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Entangling Roots",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[393456] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Entrapment",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[118699] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Fear",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[211881] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Fel Eruption",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[33395] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Freeze",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[122] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Frost Nova",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[3355] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Freezing Trap",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[1330] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Garrote - Silence",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[91800] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Gnaw",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[1776] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Gouge",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[473291] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Gravity Lapse",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[853] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Hammer of Justice",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[287712] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Haymaker",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[51514] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Hex",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[2637] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Hibernate",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[200200] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Holy Word: Chastise",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[5484] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Howl of Terror",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[157997] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Ice Nova",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[454787] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Ice Prison",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[217832] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Imprison",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[99] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Incapacitating Roar",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[22703] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Infernal Awakening",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[5246] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Intimidating Shout",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[316595] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Intimidating Shout",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[316593] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Intimidating Shout",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[24394] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Intimidation",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[408] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Kidney Shot",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[355689] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Landslide",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[119381] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Leg Sweep",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[305485] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Lightning Lasso",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[203123] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Maim",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[102359] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Mass Entanglement",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[383121] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Mass Polymorph",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[200166] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Metamorphosis",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[5211] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Mighty Bash",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[453] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Mind Soothe",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[91797] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Monstrous Blow",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[6789] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Mortal Coil",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[115078] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Paralysis",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[118] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Polymorph",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[64044] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Psychic Horror",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[8122] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Psychic Scream",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[107079] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Quaking Palm",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[20066] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Repentance",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[82691] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Ring of Frost",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[6770] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Sap",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[213691] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Scatter Shot",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[6358] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Seduction",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[9484] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Shackle Undead",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[30283] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Shadowfury",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[91807] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Shambling Rush",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[385954] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Shield Charge",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[132168] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Shockwave",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[207685] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Sigil of Misery",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[204490] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Sigil of Silence",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[15487] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Silence",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[360806] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Sleep Walk",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[81261] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Solar Beam",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[198909] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Song of Chi-Ji",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[118905] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Static Charge",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[132169] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Storm Bolt",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[197214] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Sundering",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[372245] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Terror of the Skies",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[374776] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Tightening Grasp",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[10326] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Turn Evil",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[114404] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Void Tendril's Grasp",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[20549] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "War Stomp",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[370970] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "The Hunt",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconGroups"] = {
	true,
	},
	["customBorderPath"] = "",
	["customBorderType"] = 3,
	["glowType"] = 3,
	["iconSizeHeight"] = 42,
	},
	nil,
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[463061] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Bloodthirsty Cackle",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconGroups"] = {
	true,
	},
	["customBorderPath"] = "",
	["customBorderType"] = 3,
	["glowType"] = 3,
	["iconSizeHeight"] = 42,
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[357229] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Chronolight Enhancer",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[353706] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Rowdy",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[347775] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Spam Filter",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[355640] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Phalanx Field",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[355888] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Hard Light Baton",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[1244446] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Force Multiplier",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[355147] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Fish Invigoration",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[355057] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Cry of Mrrggllrrgg",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[428150] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Reflective Shield",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconGroups"] = {
	true,
	},
	["customBorderPath"] = "",
	["customBorderType"] = 3,
	["glowType"] = 3,
	["iconSizeHeight"] = 42,
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[356133] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Super Saison",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[1240214] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Double Time",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[1221133] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Hungering Rage",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[422969] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Vindictive Wrath",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconGroups"] = {
	true,
	},
	["customBorderPath"] = "",
	["customBorderType"] = 3,
	["glowType"] = 3,
	["iconSizeHeight"] = 42,
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[207771] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Fiery Brand",
	["showOnPlayers"] = true,
	["enabledState"] = 3,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconGroups"] = {
	true,
	},
	["customBorderPath"] = "",
	["customBorderType"] = 3,
	["glowType"] = 3,
	["iconSizeHeight"] = 42,
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[451112] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Tactician's Rage",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconGroups"] = {
	true,
	},
	["customBorderPath"] = "",
	["customBorderType"] = 3,
	["glowType"] = 3,
	["iconSizeHeight"] = 42,
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[1223000] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Embrace of K'aresh",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconSizeHeight"] = 42,
	["glowType"] = 3,
	["customBorderType"] = 3,
	["customBorderPath"] = "",
	["iconGroups"] = {
	true,
	},
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[326450] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Loyal Beasts",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconGroups"] = {
	true,
	},
	["customBorderPath"] = "",
	["customBorderType"] = 3,
	["glowType"] = 3,
	["iconSizeHeight"] = 42,
	},
	{
	["customBorderColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["checkSpellID"] = {
	[117405] = true,
	},
	["showOnPets"] = true,
	["animationType"] = 2,
	["iconSizeWidth"] = 42,
	["showOnNpcs"] = true,
	["spellName"] = "Binding Shot",
	["showOnPlayers"] = true,
	["enabledState"] = 2,
	["auraType"] = 3,
	["showOnEnemies"] = true,
	["animationDisplayMode"] = 1,
	["showOnFriends"] = true,
	["customBorderSize"] = 1,
	["animationTimer"] = 10,
	["iconGroups"] = {
	true,
	},
	["customBorderPath"] = "",
	["customBorderType"] = 3,
	["glowType"] = 3,
	["iconSizeHeight"] = 42,
	},
	},
	["DefaultSpellsLastSetImported"] = 4,
	["IconGroups"] = {
	{
	["StacksTextAnchor"] = "TOP",
	["InterruptsEnabled"] = false,
	["BorderFilePath"] = "Interface\\AddOns\\NameplateAuras\\media\\custom-example.tga",
	["StacksFontScale"] = 1.4,
	["Additions_DRPvP"] = false,
	["UseTargetAlphaIfNotTargetSelected"] = false,
	["InterruptsIconSizeHeight"] = 45,
	["TimerTextUseRelativeScale"] = true,
	["TimerTextYOffset"] = 0,
	["Additions_DispellableSpells_Blacklist"] = {
	},
	["Additions_DispellableSpells"] = false,
	["DebuffBordersMagicColor"] = {
	0,
	0,
	0,
	1,
	},
	["TimerTextSize"] = 20,
	["StacksTextColor"] = {
	1,
	1,
	1,
	1,
	},
	["TimerTextUseRelativeColor"] = false,
	["BorderThickness"] = 1,
	["NonTargetStrata"] = "MEDIUM",
	["BorderType"] = 1,
	["ShowCooldownSwipeEdge"] = true,
	["AttachType"] = 1,
	["TimerTextUnderMinuteColor"] = {
	1,
	1,
	0.1,
	1,
	},
	["ShowBuffBorders"] = true,
	["TimerTextAnchor"] = "CENTER",
	["TimerTextLongerColor"] = {
	0.7,
	1,
	0,
	1,
	},
	["FrameAnchor"] = "CENTER",
	["FontScale"] = 1,
	["StacksTextAnchorIcon"] = "TOP",
	["Font"] = "GothamNarrowUltra",
	["ShowAuraTooltip"] = false,
	["MasqueEnabled"] = false,
	["StacksTextYOffset"] = 5,
	["DebuffBordersOtherColor"] = {
	0,
	0,
	0,
	1,
	},
	["TimerTextColorZeroPercent"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["IconScaleTarget"] = 1,
	["DebuffBordersDiseaseColor"] = {
	0,
	0,
	0,
	1,
	},
	["FriendlyUnitsAurasEnabledZoneTypes"] = {
	["none"] = false,
	["party"] = false,
	["scenario"] = false,
	["pvp_bg_40ppl"] = false,
	["unknown"] = false,
	["arena"] = false,
	["raid"] = false,
	["pvp"] = false,
	},
	["InterruptsUseSharedIconTexture"] = false,
	["FrameAnchorToNameplate"] = "CENTER",
	["InterruptsGlowType"] = 1,
	["TimerTextXOffset"] = 0,
	["AlwaysShowMyAuras"] = false,
	["IconGrowDirection"] = 1,
	["TimerTextSoonToExpireColor"] = {
	1,
	0.1,
	0.1,
	1,
	},
	["IconAnchor"] = 3,
	["StacksFont"] = "Naowh",
	["StacksTextXOffset"] = 0,
	["CustomSortMethod"] = "function(aura1, aura2) return aura1.spellName < aura2.spellName; end",
	["TargetStrata"] = "HIGH",
	["DebuffBordersPoisonColor"] = {
	0,
	0,
	0,
	1,
	},
	["MinTimeToShowTenthsOfSeconds"] = 0,
	["IconZoom"] = 0.1,
	["BuffBordersColor"] = {
	0,
	0,
	0,
	1,
	},
	["AlwaysShowMyAurasBlacklist"] = {
	},
	["ShowOnlyOnTarget"] = false,
	["Additions_ExplosiveOrbs"] = false,
	["ShowAurasOnPlayerNameplate"] = false,
	["EnemyUnitsAurasEnabledZoneTypes"] = {
	["none"] = true,
	["party"] = true,
	["scenario"] = true,
	["pvp_bg_40ppl"] = true,
	["unknown"] = true,
	["arena"] = true,
	["raid"] = true,
	["pvp"] = true,
	},
	["SortMode"] = 2,
	["InterruptsShowOnlyOnPlayers"] = true,
	["Additions_DRPvE"] = false,
	["AffixSpiteful"] = true,
	["DispelIconSizeWidth"] = 45,
	["IconXOffset"] = 0,
	["IconYOffset"] = 24,
	["ShowAurasOnEnemyTargetEvenInDisabledAreas"] = false,
	["IconSpacing"] = 2,
	["AffixSpitefulSound"] = 5274,
	["InterruptsIconSizeWidth"] = 45,
	["Additions_DispellableSpells_GlowType"] = 4,
	["DispelIconSizeHeight"] = 45,
	["ShowCooldownAnimation"] = true,
	["IconAlphaTarget"] = 1,
	["IconAlpha"] = 1,
	["ShowCooldownText"] = true,
	["ShowStacks"] = true,
	["DefaultIconSizeHeight"] = 42,
	["DebuffBordersCurseColor"] = {
	0,
	0,
	0,
	1,
	},
	["ShowDebuffBorders"] = true,
	["IconGroupName"] = "First Icon Group",
	["Additions_Dispel_InstanceTypes"] = {
	["none"] = true,
	["party"] = true,
	["scenario"] = true,
	["pvp_bg_40ppl"] = true,
	["unknown"] = true,
	["arena"] = true,
	["raid"] = true,
	["pvp"] = true,
	},
	["NpcBlacklist"] = {
	},
	["TimerTextAnchorIcon"] = "CENTER",
	["TimerTextColorHundredPercent"] = {
	0.1,
	1,
	0.1,
	1,
	},
	["KeepAspectRatio"] = true,
	["UseDefaultAuraTooltip"] = false,
	["NameplateIsParent"] = false,
	["ShowAurasOnAlliedTargetEvenInDisabledAreas"] = false,
	["DefaultIconSizeWidth"] = 42,
	},
	},
	["HidePlayerBlizzardFrame"] = true,
	["DBVersion"] = 34,
}